# logging configuration
logging:
  file:
    name: "logs/meil.log"
  logback:
    rollingpolicy:
      max-file-size: 50MB
  level:
    web: debug
    root: warn
    org.hibernate: error
    org.hibernate.sql: error

# spring configuration
spring:
  devtools:
    livereload:
      enabled: false

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/meil
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: embedded

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQLDialect"
    defer-datasource-initialization: true


  main:
    allow-circular-references: true

  jackson:
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false

jwt:
  secret: "my-ultra-strong-jwt-secret-for-meil"
  issuer: "meil"

# enable graceful shutdown
server:
  shutdown: graceful

# actuator shutdown
management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*" # or "health,info,shutdown"